### PR TITLE
Use hook_localgov_roles to assign topic permissions to localgov_editor role

### LINKED ISSUE #27: Add missing permissions for editors (and other roles?)
See https://github.com/localgovdrupal/localgov/issues/677

Currently in a default setup editors cannot edit any of these topic terms.
Suggest adding a hook_localgov_roles and adding `create terms in localgov_topic`, `delete terms in localgov_topic`,  `edit terms in localgov_topic`

Suggest at least for localgov_editors but may be useful for other roles?

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #27

Add default permissions to editor role.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Questions.
Should we also add these permissions to other roles?
Do we need to add tests for this?

**Comment by finnlewis** [comment]
This is probably a good question to ask @willguv and the product group.

On a default installation, the 'Content editor' role can only manage content, not the 'topics' taxonomy. This means by default, they can only assign existing terms. 

Should the 'Content editor' have more permissions to manage topics by default? Or should this be left to the developers to manage and pre-define the topics? 

Alternatively, might we want to add another role 'Taxonomy manager' or 'Website manager' with more power to manage taxonomies in  general?

**Comment by finnlewis** [comment]
Note from @rupertj - at H&F they do use topics, and the editors cannot manage the topics. So the topics were predefined at launch.

**Comment by andybroomfield** [comment]
Just to note that the editor will also need `access taxonomy overview` and `access administration pages` to actully use the taxonomy menu items.

**Comment by finnlewis** [comment]
@willguv could you review the questions above and respond? We're going to wait for your guidance on this,.

**Comment by willguv** [comment]
Hi @finnlewis and all, thanks for flagging this

Quick answer

- if councils have a full time professional content designer set up, they need to be able to create and edit topics. It's something we've needed to add in most of the councils I've worked for
- we know though that some councils devolve editing and they're probably running a closed taxonomy

Therefore safest is to create a new 'Taxonomy manager' role

**Comment by andybroomfield** [comment]
If we want to create a taxonomy manager role, do we want to add the role to this module, or add it to localgov_roles since that role might want to be re-used for the events taxonomy and potentially managing directory facets.

**Comment by willguv** [comment]
@finnlewis who needs to review this please?

**Review by stephen-cox — COMMENTED** [review]
If we're happy just giving the Editor role permissions to manage Topics then this does the job. If we want an extra role for this then, as @andybroomfield mentioned, perhaps we should create a taxonomy manager role and move this to the localgov_roles module.

**Comment by willguv** [comment]
@stephen-cox would be good to clear this down

Does this need a review from you please, or extra work? Thanks

**Review by ekes — APPROVED** [review]
MT happy with it going to editor.

**Pull request merged**
